# -*- coding: utf-8 -*-
"""cancer analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DbTrB6OaatB2MDEdmLs10C6EWYi3nRUy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_ind, chi2_contingency, f_oneway, spearmanr
import warnings
warnings.filterwarnings('ignore')

plt.rcParams.update({'figure.dpi': 120,
                     'axes.spines.top': False,
                     'axes.spines.right': False})
BLUE  = '#2C6E96'
RED   = '#E05A2B'
GREEN = '#2E8B57'
GOLD  = '#D4A017'
PURPL = '#6A3D7A'
GREY  = '#B0B0B0'
sns.set_style('whitegrid')

DATA_PATH = '/content/Breast_Cancer_METABRIC_Epic_Hospital.csv'
df_raw = pd.read_csv(DATA_PATH)
print(f'Loaded: {df_raw.shape[0]:,} rows x {df_raw.shape[1]} columns')
print('\nAll columns:')
for i, c in enumerate(df_raw.columns, 1):
    print(f'  {i:2d}. {c}')



"""# Data inspection"""

display(df_raw.head())
display(df_raw.dtypes.to_frame('dtype'))
print(f'\nNumerical : {df_raw.select_dtypes("number").shape[1]}')
print(f'Categorical: {df_raw.select_dtypes("object").shape[1]}')

missing     = df_raw.isnull().sum()
missing_pct = (missing / len(df_raw) * 100).round(2)
missing_df  = pd.DataFrame({'Count': missing, 'Percent': missing_pct})
missing_df  = missing_df[missing_df['Count'] > 0].sort_values('Percent', ascending=False)
display(missing_df)

fig, axes = plt.subplots(1, 2, figsize=(14, 4))
axes[0].barh(missing_df.index, missing_df['Percent'], color=RED)
axes[0].axvline(5, color='black', linestyle='--', alpha=0.5, label='5% line')
axes[0].set_xlabel('Missing %')
axes[0].set_title('Missing Values by Column')
axes[0].legend()
sample = df_raw[missing_df.index].sample(200, random_state=42)
sns.heatmap(sample.isnull(), cbar=False, cmap='OrRd',
            ax=axes[1], yticklabels=False)
axes[1].set_title('Missing Pattern (200-row sample)')
plt.tight_layout()
plt.savefig('missing_values.png', bbox_inches='tight')
plt.show()
print('Finding: Max missingness <1% — excellent data quality for clinical research.')

for c in df_raw.select_dtypes('object').columns:
    uv = df_raw[c].unique()
    print(f'  {c:<42s} ({len(uv)} unique): {list(uv[:5])}')



"""# Data Cleaning"""

df = df_raw.copy()
df.columns = df.columns.str.strip()

# Binary-encode treatment flags
for col in ['Chemotherapy', 'Hormone Therapy', 'Radio Therapy']:
    df[col + '_bin'] = (df[col] == 'Yes').astype(int)

# Mortality & survival flags
df['died_of_disease'] = (df["Patient's Vital Status"] == 'Died of Disease').astype(int)
df['any_deceased']    = (df['Overall Survival Status'] == 'Deceased').astype(int)

# Receptor status
df['ER_pos']   = (df['ER Status'] == 'Positive').astype(int)
df['HER2_pos'] = (df['HER2 Status'] == 'Positive').astype(int)
df['PR_pos']   = (df['PR Status'] == 'Positive').astype(int)
df['triple_negative'] = (
    (df['ER_pos'] == 0) & (df['HER2_pos'] == 0) & (df['PR_pos'] == 0)
).astype(int)

df_clean = df.dropna(subset=['Tumor Stage', 'Age at Diagnosis', 'Tumor Size']).copy()
df_clean['Tumor Stage'] = df_clean['Tumor Stage'].astype(int)

print(f'Rows after cleaning: {df_clean.shape[0]:,} (dropped {df.shape[0] - df_clean.shape[0]})')
print('Engineered: Chemotherapy_bin, Hormone Therapy_bin, Radio Therapy_bin,')
print('  died_of_disease, any_deceased, ER_pos, HER2_pos, PR_pos, triple_negative')

df[['Overall Survival (Months)',
    'Overall Survival Status']].head()

print(df['Overall Survival Status'].value_counts())

print(df['Relapse Free Status'].value_counts())

# ============================================================
# ADDITIONAL DATA CLEANING & CLINICAL COHORT ENGINEERING
# ============================================================

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ============================================================
# 1. SURVIVAL VARIABLE VALIDATION
# ============================================================

print("="*60)
print("SURVIVAL VARIABLE VALIDATION")
print("="*60)

print("\nOverall Survival Status:")
print(df_clean['Overall Survival Status'].value_counts(dropna=False))

print("\nRelapse Free Status:")
print(df_clean['Relapse Free Status'].value_counts(dropna=False))

print("\nChecking negative survival times...")

neg_os = (df_clean['Overall Survival (Months)'] < 0).sum()
neg_rfs = (df_clean['Relapse Free Status (Months)'] < 0).sum()

print(f"Negative Overall Survival Times : {neg_os}")
print(f"Negative Relapse-Free Times     : {neg_rfs}")

# ============================================================
# 2. OUTLIER ANALYSIS USING IQR
# ============================================================

print("\n" + "="*60)
print("OUTLIER ANALYSIS")
print("="*60)

numeric_cols = [
    'Age at Diagnosis',
    'Tumor Size',
    'Mutation Count',
    'Lymph nodes examined positive'
]

for col in numeric_cols:

    if col in df_clean.columns:

        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)

        IQR = Q3 - Q1

        lower = Q1 - 1.5*IQR
        upper = Q3 + 1.5*IQR

        outliers = ((df_clean[col] < lower) |
                    (df_clean[col] > upper)).sum()

        print(f"{col:<35} Outliers = {outliers}")

# ============================================================
# BOXPLOTS
# ============================================================

fig, axes = plt.subplots(2,2, figsize=(12,8))

for ax, col in zip(axes.flatten(), numeric_cols):

    if col in df_clean.columns:

        sns.boxplot(
            x=df_clean[col],
            ax=ax
        )

        ax.set_title(col)

plt.tight_layout()
plt.show()

# ============================================================
# 3. CATEGORY STANDARDIZATION
# ============================================================

print("\n" + "="*60)
print("CATEGORY STANDARDIZATION")
print("="*60)

cat_cols = [
    'ER Status',
    'PR Status',
    'HER2 Status',
    'Chemotherapy',
    'Hormone Therapy',
    'Radio Therapy'
]

for col in cat_cols:

    if col in df_clean.columns:

        df_clean[col] = (
            df_clean[col]
            .astype(str)
            .str.strip()
            .str.title()
        )

        print(f"\n{col}")
        print(df_clean[col].value_counts())

# ============================================================
# 4. AGE GROUP CREATION
# ============================================================

df_clean['Age_Group'] = pd.cut(

    df_clean['Age at Diagnosis'],

    bins=[0,40,60,120],

    labels=[
        '<40',
        '40-60',
        '>60'
    ]
)

print("\nAge Groups")
print(df_clean['Age_Group'].value_counts())

# ============================================================
# 5. TUMOR SIZE GROUPS
# ============================================================

df_clean['Tumor_Size_Group'] = pd.cut(

    df_clean['Tumor Size'],

    bins=[0,20,50,500],

    labels=[
        'Small',
        'Medium',
        'Large'
    ]
)

print("\nTumor Size Groups")
print(df_clean['Tumor_Size_Group'].value_counts())

# ============================================================
# 6. EARLY VS LATE STAGE COHORT
# ============================================================

df_clean['Stage_Group'] = np.where(

    df_clean['Tumor Stage'] <= 2,

    'Early Stage',

    'Late Stage'
)

print("\nStage Groups")
print(df_clean['Stage_Group'].value_counts())

# ============================================================
# 7. RETENTION RATE
# ============================================================

rows_before = len(df)
rows_after = len(df_clean)

retention = round(
    rows_after/rows_before*100,
    2
)

print("\n" + "="*60)
print("DATA RETENTION")
print("="*60)

print(f"Original Rows : {rows_before:,}")
print(f"Final Rows    : {rows_after:,}")
print(f"Retention Rate: {retention}%")

# ============================================================
# 8. BASELINE CHARACTERISTICS TABLE
# ============================================================

print("\n" + "="*60)
print("BASELINE CHARACTERISTICS")
print("="*60)

baseline = pd.DataFrame({

    'Mean Age':
        [round(df_clean['Age at Diagnosis'].mean(),2)],

    'Median Age':
        [round(df_clean['Age at Diagnosis'].median(),2)],

    'Mean Tumor Size':
        [round(df_clean['Tumor Size'].mean(),2)],

    'Median Survival':
        [round(df_clean['Overall Survival (Months)'].median(),2)],

    'Patients':
        [len(df_clean)]
})

display(baseline)

# ============================================================
# 9. CLINICAL READINESS SUMMARY
# ============================================================

print("\n" + "="*60)
print("CLINICAL DATASET READY FOR:")
print("="*60)

print("✓ Descriptive Statistics")
print("✓ Hypothesis Testing")
print("✓ Kaplan-Meier Survival Analysis")
print("✓ Log-Rank Testing")
print("✓ Cox Proportional Hazards Modeling")
print("✓ Relapse-Free Survival Analysis")

# Event Rates

death_rate = (
    df_clean['any_deceased'].mean()*100
)

recurrence_rate = (
    (df_clean['Relapse Free Status']=="Recurred")
    .mean()*100
)

print(f"Mortality Rate : {death_rate:.2f}%")
print(f"Recurrence Rate: {recurrence_rate:.2f}%")

"""# data quality assessmewnt

"""

completeness = (1 - df_raw.isnull().mean()) * 100
print(f'Overall completeness   : {completeness.mean():.2f}%')
print(f'Min column completeness: {completeness.min():.2f}%  ({completeness.idxmin()})')
print(f'Fully complete columns : {(completeness == 100).sum()} / {len(df_raw.columns)}')
dups = df_raw.duplicated(subset='Patient ID').sum()
print(f'Duplicate Patient IDs  : {dups}')

checks = {
    'Age at Diagnosis'         : (18, 100),
    'Overall Survival (Months)': (0, 500),
    'Tumor Size'               : (0, 200),
    'Mutation Count'           : (0, 5000),
}
print('\nRange checks:')
for col, (lo, hi) in checks.items():
    out = ((df_raw[col] < lo) | (df_raw[col] > hi)).sum()
    icon = 'OK' if out == 0 else f'WARN: {out} outliers'
    print(f'  {col:<35s} [{lo}-{hi}]  {icon}')
print('\nConclusion: Data quality HIGH — suitable for clinical publication-grade analysis.')

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].hist(df_clean['Age at Diagnosis'], bins=35, color=BLUE, edgecolor='white')
med_age = df_clean['Age at Diagnosis'].median()
axes[0].axvline(med_age, color='red', linestyle='--',
                label=f'Median={med_age:.1f}')
axes[0].set_xlabel('Age at Diagnosis')
axes[0].set_ylabel('Count')
axes[0].set_title('Age — Histogram')
axes[0].legend()

sns.kdeplot(data=df_clean, x='Age at Diagnosis',
            fill=True, color=BLUE, alpha=0.6, ax=axes[1])
axes[1].set_title('Age — Density')

sns.boxplot(data=df_clean, x='Inferred Menopausal State',
            y='Age at Diagnosis',
            palette=[GREEN, RED], ax=axes[2])
axes[2].set_title('Age by Menopausal State')

plt.tight_layout()
plt.savefig('eda_age.png', bbox_inches='tight')
plt.show()
mean_age = df_clean['Age at Diagnosis'].mean()
post_pct = (df_clean['Inferred Menopausal State'] == 'Post').mean() * 100
print(f'Mean age: {mean_age:.1f} yrs  |  Post-menopausal: {post_pct:.1f}%')

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].hist(df_clean['Tumor Size'], bins=40, color=PURPL, edgecolor='white')
med_ts = df_clean['Tumor Size'].median()
axes[0].axvline(med_ts, color='red', linestyle='--',
                label=f'Median={med_ts:.0f} mm')
axes[0].set_xlabel('Tumor Size (mm)')
axes[0].set_title('Tumor Size Distribution')
axes[0].legend()

sns.boxplot(data=df_clean, x='Tumor Stage', y='Tumor Size',
            palette='Blues', ax=axes[1])
axes[1].set_title('Tumor Size by Stage')
axes[1].set_xlabel('Tumor Stage')

grade_cnt = df_clean['Neoplasm Histologic Grade'].value_counts().sort_index()
axes[2].bar(grade_cnt.index.astype(str), grade_cnt.values,
            color=[GREEN, GOLD, RED])
axes[2].set_title('Histologic Grade Distribution')
axes[2].set_xlabel('Grade')
for i, v in enumerate(grade_cnt.values):
    axes[2].text(i, v + 30, f'{v:,}', ha='center', fontsize=9)

plt.tight_layout()
plt.savefig('eda_tumor.png', bbox_inches='tight')
plt.show()
g3_pct = (df_clean['Neoplasm Histologic Grade'] == 3).mean() * 100
print(f'Grade 3 (high-grade): {g3_pct:.1f}%  |  Median tumor: {med_ts:.0f} mm')

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
tx_list = [
    ('Chemotherapy',   RED,   'Chemotherapy'),
    ('Hormone Therapy', GREEN, 'Hormone Therapy'),
    ('Radio Therapy',  PURPL, 'Radio Therapy'),
]
for ax, (col, color, label) in zip(axes, tx_list):
    counts = df_clean[col].value_counts()
    pct    = counts / counts.sum() * 100
    ax.bar(counts.index, counts.values, color=[color, GREY])
    ax.set_title(label)
    ax.set_ylabel('Count')
    for i, (v, p) in enumerate(zip(counts.values, pct.values)):
        ax.text(i, v + 30, f'{p:.1f}%', ha='center', fontweight='bold')

plt.suptitle('Treatment Modalities — 15,054 Patients', fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig('eda_treatment.png', bbox_inches='tight')
plt.show()
for col in ['Chemotherapy', 'Hormone Therapy', 'Radio Therapy']:
    p = (df_clean[col] == 'Yes').mean() * 100
    print(f'{col}: {p:.1f}% received')

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

receptor_data = {
    'ER+'         : df_clean['ER_pos'].mean() * 100,
    'PR+'         : df_clean['PR_pos'].mean() * 100,
    'HER2+'       : df_clean['HER2_pos'].mean() * 100,
    'Triple-Neg'  : df_clean['triple_negative'].mean() * 100,
}
axes[0].bar(receptor_data.keys(), receptor_data.values(),
            color=[BLUE, GREEN, RED, 'black'])
axes[0].set_ylabel('% Patients')
axes[0].set_title('Receptor Status Prevalence')
for i, v in enumerate(receptor_data.values()):
    axes[0].text(i, v + 1, f'{v:.1f}%', ha='center', fontweight='bold')

pam50 = df_clean['Pam50 + Claudin-low subtype'].value_counts()
axes[1].barh(pam50.index, pam50.values,
             color=sns.color_palette('Set2', len(pam50)))
axes[1].set_title('PAM50 Molecular Subtypes')
axes[1].set_xlabel('Count')

tn_mort = df_clean.groupby('triple_negative')['died_of_disease'].mean() * 100
axes[2].bar(['Non-TN', 'Triple Negative'], tn_mort.values,
            color=[GREEN, 'crimson'])
axes[2].set_title('Disease Mortality by TN Status')
axes[2].set_ylabel('% Died of Disease')
for i, v in enumerate(tn_mort.values):
    axes[2].text(i, v + 0.5, f'{v:.1f}%', ha='center', fontweight='bold')

plt.tight_layout()
plt.savefig('eda_molecular.png', bbox_inches='tight')
plt.show()
print(f'TN mortality: {tn_mort[1]:.1f}% vs {tn_mort[0]:.1f}% non-TN  (delta={tn_mort[1]-tn_mort[0]:.1f} pp)')

fig, axes = plt.subplots(1, 3, figsize=(15, 4))

axes[0].hist(df_clean['Overall Survival (Months)'],
             bins=50, color=BLUE, edgecolor='white')
med_os = df_clean['Overall Survival (Months)'].median()
axes[0].axvline(med_os, color='red', linestyle='--',
                label=f'Median={med_os:.0f} mo')
axes[0].set_xlabel('Overall Survival (Months)')
axes[0].set_title('Survival Duration Distribution')
axes[0].legend()

sns.boxplot(data=df_clean, x='Tumor Stage',
            y='Overall Survival (Months)', palette='RdYlGn', ax=axes[1])
axes[1].set_title('Survival by Tumor Stage')

vs = df_clean["Patient's Vital Status"].value_counts().dropna()
colors_pie = [GREEN, 'crimson', GOLD, GREY]
axes[2].pie(vs.values, labels=vs.index, autopct='%1.1f%%',
            colors=colors_pie[:len(vs)], startangle=90,
            wedgeprops={'edgecolor': 'white', 'linewidth': 1.5})
axes[2].set_title("Vital Status Distribution")

plt.tight_layout()
plt.savefig('eda_survival.png', bbox_inches='tight')
plt.show()
for s, c in vs.items():
    print(f'  {s:<30s}: {c:,} ({c/vs.sum()*100:.1f}%)')



"""# Descriptive statistics"""

num_cols = [
    'Age at Diagnosis', 'Tumor Size', 'Neoplasm Histologic Grade',
    'Lymph nodes examined positive', 'Mutation Count',
    'Nottingham prognostic index', 'Overall Survival (Months)',
    'Relapse Free Status (Months)'
]
desc = df_clean[num_cols].describe().T
desc['IQR'] = desc['75%'] - desc['25%']
desc['CV%'] = (desc['std'] / desc['mean'] * 100).round(1)
out = desc[['count','mean','50%','std','IQR','min','max','CV%']].rename(
    columns={'50%': 'median', 'count': 'n'}).round(2)
print('=== DESCRIPTIVE STATISTICS (all numeric variables) ===')
display(out)

def freq_table(series, label):
    vc  = series.value_counts(dropna=False)
    pct = (vc / len(series) * 100).round(1)
    tbl = pd.DataFrame({'Count': vc, 'Percent (%)': pct})
    print(f'\n{"-"*50}\n  {label}\n{"-"*50}')
    display(tbl)

freq_table(df_clean['Neoplasm Histologic Grade'], 'Histologic Grade')
freq_table(df_clean['Tumor Stage'], 'Tumor Stage')
freq_table(df_clean['Pam50 + Claudin-low subtype'], 'PAM50 Subtype')
freq_table(df_clean["Patient's Vital Status"], 'Vital Status')
freq_table(df_clean['Chemotherapy'], 'Chemotherapy')
freq_table(df_clean['Hormone Therapy'], 'Hormone Therapy')

print('=== SURVIVAL BY TUMOR STAGE ===')
display(df_clean.groupby('Tumor Stage')['Overall Survival (Months)'].agg(
    ['count','mean','median','std']).round(2))

print('\n=== TUMOR SIZE BY GRADE ===')
display(df_clean.groupby('Neoplasm Histologic Grade')['Tumor Size'].agg(
    ['count','mean','median','std']).round(2))

print('\n=== SURVIVAL BY PAM50 SUBTYPE ===')
display(df_clean.groupby('Pam50 + Claudin-low subtype')[
    'Overall Survival (Months)'].agg(
    ['count','mean','median','std']).sort_values('mean', ascending=False).round(2))

print('\n=== MUTATION COUNT BY VITAL STATUS ===')
display(df_clean.groupby("Patient's Vital Status")['Mutation Count'].agg(
    ['count','mean','median','std']).round(2))

fig, axes = plt.subplots(2, 2, figsize=(14, 9))

sub_ord = (df_clean.groupby('Pam50 + Claudin-low subtype')
           ['Overall Survival (Months)'].median()
           .sort_values(ascending=False).index)
sns.boxplot(data=df_clean, x='Pam50 + Claudin-low subtype',
            y='Overall Survival (Months)',
            order=sub_ord, palette='Set2', ax=axes[0, 0])
axes[0,0].set_xticklabels(axes[0,0].get_xticklabels(),
                          rotation=30, ha='right', fontsize=8)
axes[0,0].set_title('Survival by PAM50 Subtype')
axes[0,0].set_xlabel('')

sns.boxplot(data=df_clean, x='Neoplasm Histologic Grade',
            y='Mutation Count',
            palette=[GREEN, GOLD, RED], ax=axes[0, 1])
axes[0,1].set_title('Mutation Count by Histologic Grade')

plot_df = df_clean[df_clean["Patient's Vital Status"].isin(
    ['Living', 'Died of Disease'])]
sns.kdeplot(data=plot_df, x='Nottingham prognostic index',
            hue="Patient's Vital Status", fill=True, alpha=0.5,
            palette={'Living': GREEN, 'Died of Disease': 'crimson'},
            ax=axes[1, 0])
axes[1,0].set_title('NPI Distribution by Vital Status')

sns.boxplot(data=df_clean, x='Tumor Stage',
            y='Lymph nodes examined positive',
            palette='Blues', ax=axes[1, 1])
axes[1,1].set_title('Positive Lymph Nodes by Tumor Stage')

plt.suptitle('Descriptive Statistics — Clinical Comparisons', fontsize=13, y=1.01)
plt.tight_layout()
plt.savefig('descriptive_stats.png', bbox_inches='tight')
plt.show()

"""# Hypothesis testing

## Independent T tests
"""

print('=' * 65)
print('INDEPENDENT t-TESTS')
print('=' * 65)

def run_ttest(df, gcol, vcol, g1, g2, label):
    a = df[df[gcol] == g1][vcol].dropna()
    b = df[df[gcol] == g2][vcol].dropna()
    t, p = ttest_ind(a, b, equal_var=False)
    diff = a.mean() - b.mean()
    pooled_sd = np.sqrt((a.std()**2 + b.std()**2) / 2)
    d = diff / pooled_sd
    sig = 'SIGNIFICANT' if p < 0.05 else 'Not significant'
    print(f'\n{label}')
    print(f'  {g1}: n={len(a):,}  mean={a.mean():.2f}  SD={a.std():.2f}')
    print(f'  {g2}: n={len(b):,}  mean={b.mean():.2f}  SD={b.std():.2f}')
    print(f'  Delta={diff:.2f}  t={t:.3f}  p={p:.4e}  Cohen d={d:.3f}')
    print(f'  Result: {sig}')
    return dict(label=label, g1=g1, g2=g2,
                mean_g1=a.mean(), mean_g2=b.mean(),
                delta=diff, t=t, p=p, cohens_d=d)

tt_res = []

# H1
tt_res.append(run_ttest(df_clean, 'Chemotherapy',
    'Overall Survival (Months)', 'Yes', 'No',
    'H1: Survival ~ Chemotherapy (Yes vs No)'))

# H2
plot_df2 = df_clean[df_clean["Patient's Vital Status"].isin(
    ['Living', 'Died of Disease'])]
tt_res.append(run_ttest(plot_df2, "Patient's Vital Status",
    'Tumor Size', 'Died of Disease', 'Living',
    'H2: Tumor Size ~ Vital Status (Died-Disease vs Living)'))

# H3
tt_res.append(run_ttest(df_clean, 'ER Status',
    'Nottingham prognostic index', 'Positive', 'Negative',
    'H3: NPI ~ ER Status (Positive vs Negative)'))

# H4
df_g13 = df_clean[df_clean['Neoplasm Histologic Grade'].isin([1, 3])].copy()
df_g13['G'] = df_g13['Neoplasm Histologic Grade'].astype(str)
tt_res.append(run_ttest(df_g13, 'G', 'Mutation Count', '3', '1',
    'H4: Mutation Count ~ Grade 3 vs Grade 1'))

# H5
tt_res.append(run_ttest(df_clean, 'HER2 Status',
    'Overall Survival (Months)', 'Positive', 'Negative',
    'H5: Survival ~ HER2 Status'))

# H6
tt_res.append(run_ttest(df_clean, 'Chemotherapy',
    'Lymph nodes examined positive', 'Yes', 'No',
    'H6: Positive Lymph Nodes ~ Chemotherapy Use'))

tt_df = pd.DataFrame(tt_res)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
colors = [RED if p < 0.05 else GREY for p in tt_df['p']]

axes[0].barh(tt_df['label'].str[:52], tt_df['delta'], color=colors)
axes[0].axvline(0, color='black', linewidth=1)
axes[0].set_xlabel('Mean Difference (G1 - G2)')
axes[0].set_title('t-Test: Mean Differences\n(red = p<0.05)')
axes[0].tick_params(axis='y', labelsize=7)

axes[1].barh(tt_df['label'].str[:52],
             -np.log10(tt_df['p'].clip(1e-300)), color=colors)
axes[1].axvline(-np.log10(0.05), color='black',
                linestyle='--', label='p=0.05 threshold')
axes[1].set_xlabel('-log10(p-value)')
axes[1].set_title('t-Test: Statistical Significance')
axes[1].legend()
axes[1].tick_params(axis='y', labelsize=7)

plt.tight_layout()
plt.savefig('ttest_results.png', bbox_inches='tight')
plt.show()

"""# Chi-square test"""

print('=' * 65)
print('CHI-SQUARE TESTS')
print('=' * 65)

def chi2_test(df, c1, c2, label):
    ct = pd.crosstab(df[c1], df[c2])
    chi2, p, dof, _ = chi2_contingency(ct)
    n = ct.values.sum()
    r, k = ct.shape
    cramers_v = np.sqrt(chi2 / (n * (min(r, k) - 1)))
    sig = 'SIGNIFICANT' if p < 0.05 else 'Not significant'
    print(f'\n{label}')
    print(f'  chi2={chi2:.3f}  df={dof}  p={p:.4e}  CramersV={cramers_v:.3f}')
    print(f'  Result: {sig}')
    return dict(label=label, chi2=chi2, p=p, dof=dof, cramers_v=cramers_v)

chi_res = []
df_clean['vital_bin'] = df_clean["Patient's Vital Status"].map(
    {'Living': 'Living', 'Died of Disease': 'Deceased',
     'Died of Other Causes': 'Deceased'})

chi_res.append(chi2_test(
    df_clean.dropna(subset=['vital_bin']),
    'Chemotherapy', 'vital_bin',
    'H7: Chemotherapy ~ Vital Status'))
chi_res.append(chi2_test(df_clean, 'ER Status', 'Hormone Therapy',
    'H8: ER Status ~ Hormone Therapy'))
chi_res.append(chi2_test(df_clean, 'Tumor Stage', 'Neoplasm Histologic Grade',
    'H9: Tumor Stage ~ Histologic Grade'))
chi_res.append(chi2_test(df_clean, 'triple_negative', 'Chemotherapy',
    'H10: Triple-Negative ~ Chemotherapy Use'))
chi_res.append(chi2_test(
    df_clean.dropna(subset=['vital_bin', 'Pam50 + Claudin-low subtype']),
    'Pam50 + Claudin-low subtype', 'vital_bin',
    'H11: PAM50 Subtype ~ Vital Status'))
chi_res.append(chi2_test(df_clean, 'HER2 Status', 'Chemotherapy',
    'H12: HER2 Status ~ Chemotherapy Use'))

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

def plot_ct(df, c1, c2, title, ax, palette=None):
    ct = pd.crosstab(df[c1], df[c2], normalize='index') * 100
    ct.plot(kind='bar', ax=ax, color=palette, edgecolor='white')
    ax.set_title(title)
    ax.set_xlabel('')
    ax.set_ylabel('% of Patients')
    ax.tick_params(axis='x', rotation=25)
    ax.legend(fontsize=8)

plot_ct(df_clean, 'ER Status', 'Hormone Therapy',
        'H8: Hormone Therapy by ER Status', axes[0], [GREY, GREEN])
plot_ct(df_clean.dropna(subset=['vital_bin']),
        'Neoplasm Histologic Grade', 'vital_bin',
        'Vital Status by Grade', axes[1], [GREEN, 'crimson'])
plot_ct(df_clean.dropna(subset=['vital_bin']),
        'Pam50 + Claudin-low subtype', 'vital_bin',
        'H11: Vital Status by PAM50', axes[2], [GREEN, 'crimson'])
axes[2].tick_params(axis='x', rotation=40)

plt.suptitle('Chi-Square Test Visualisations', fontsize=13, y=1.02)
plt.tight_layout()
plt.savefig('chisq_results.png', bbox_inches='tight')
plt.show()

"""# ANOVA"""

print('=' * 65)
print('ONE-WAY ANOVA')
print('=' * 65)

def run_anova(df, gcol, vcol, label):
    grps = df.groupby(gcol)[vcol].apply(list)
    f, p = f_oneway(*grps.values)
    grand_mean = df[vcol].mean()
    ss_b = sum(len(g) * (np.mean(g) - grand_mean)**2 for g in grps)
    ss_t = sum((x - grand_mean)**2 for g in grps for x in g)
    eta2 = ss_b / ss_t
    means = dict(df.groupby(gcol)[vcol].mean().round(2))
    sig = 'SIGNIFICANT' if p < 0.05 else 'Not significant'
    print(f'\n{label}')
    print(f'  Group means: {means}')
    print(f'  F={f:.3f}  p={p:.4e}  eta2={eta2:.4f}')
    print(f'  Result: {sig}')
    return dict(label=label, F=f, p=p, eta2=eta2)

an_res = []
an_res.append(run_anova(df_clean, 'Tumor Stage',
    'Overall Survival (Months)', 'H13: Survival ~ Tumor Stage'))
an_res.append(run_anova(df_clean, 'Neoplasm Histologic Grade',
    'Overall Survival (Months)', 'H14: Survival ~ Histologic Grade'))
an_res.append(run_anova(
    df_clean.dropna(subset=['Pam50 + Claudin-low subtype']),
    'Pam50 + Claudin-low subtype', 'Overall Survival (Months)',
    'H15: Survival ~ PAM50 Subtype'))
an_res.append(run_anova(df_clean, 'Tumor Stage', 'Tumor Size',
    'H16: Tumor Size ~ Tumor Stage'))
an_res.append(run_anova(df_clean, 'Neoplasm Histologic Grade',
    'Mutation Count', 'H17: Mutation Count ~ Histologic Grade'))
an_res.append(run_anova(
    df_clean.dropna(subset=['Pam50 + Claudin-low subtype']),
    'Pam50 + Claudin-low subtype', 'Tumor Size',
    'H18: Tumor Size ~ PAM50 Subtype'))

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

sns.boxplot(data=df_clean, x='Tumor Stage',
            y='Overall Survival (Months)', palette='RdYlGn', ax=axes[0])
axes[0].set_title('H13: Survival by Tumor Stage\n(ANOVA p<0.001)')

sns.violinplot(data=df_clean, x='Neoplasm Histologic Grade',
               y='Overall Survival (Months)',
               palette=[GREEN, GOLD, 'crimson'], ax=axes[1])
axes[1].set_title('H14: Survival by Grade\n(ANOVA p<0.001)')

sub_ord = (df_clean.groupby('Pam50 + Claudin-low subtype')
           ['Overall Survival (Months)'].median()
           .sort_values(ascending=False).index)
sns.boxplot(data=df_clean, x='Pam50 + Claudin-low subtype',
            y='Overall Survival (Months)',
            order=sub_ord, palette='Set2', ax=axes[2])
axes[2].set_xticklabels(axes[2].get_xticklabels(),
                        rotation=35, ha='right', fontsize=7)
axes[2].set_title('H15: Survival by PAM50\n(ANOVA p<0.001)')

plt.tight_layout()
plt.savefig('anova_results.png', bbox_inches='tight')
plt.show()

"""# Correlation"
"""

print('=' * 65)
print('SPEARMAN CORRELATION ANALYSIS')
print('=' * 65)

corr_vars = [
    'Age at Diagnosis', 'Tumor Size', 'Neoplasm Histologic Grade',
    'Lymph nodes examined positive', 'Mutation Count',
    'Nottingham prognostic index', 'Overall Survival (Months)',
    'Relapse Free Status (Months)'
]
corr_matrix = df_clean[corr_vars].corr(method='spearman')

pairs = [
    ('Nottingham prognostic index', 'Overall Survival (Months)'),
    ('Tumor Size', 'Lymph nodes examined positive'),
    ('Neoplasm Histologic Grade', 'Mutation Count'),
    ('Age at Diagnosis', 'Overall Survival (Months)'),
    ('Tumor Size', 'Overall Survival (Months)'),
    ('Mutation Count', 'Overall Survival (Months)'),
]
print()
for v1, v2 in pairs:
    sub = df_clean[[v1, v2]].dropna()
    r, p = spearmanr(sub[v1], sub[v2])
    sig = '** SIGNIFICANT **' if p < 0.05 else '(not significant)'
    print(f'  {v1}  vs  {v2}')
    print(f'    rho={r:.4f}  p={p:.4e}  {sig}')

fig, axes = plt.subplots(1, 3, figsize=(17, 5))

mask = np.triu(np.ones_like(corr_matrix, dtype=bool))
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f',
            cmap='coolwarm', center=0, linewidths=0.5,
            ax=axes[0], annot_kws={'size': 7})
axes[0].set_title('Spearman Correlation Matrix')
axes[0].tick_params(labelsize=7)

sub = df_clean[['Nottingham prognostic index',
                'Overall Survival (Months)']].dropna()
r_npi, p_npi = spearmanr(
    sub['Nottingham prognostic index'], sub['Overall Survival (Months)'])
axes[1].scatter(sub['Nottingham prognostic index'],
                sub['Overall Survival (Months)'],
                alpha=0.1, s=4, color=BLUE)
m, b = np.polyfit(sub['Nottingham prognostic index'],
                  sub['Overall Survival (Months)'], 1)
xr = np.linspace(sub['Nottingham prognostic index'].min(),
                 sub['Nottingham prognostic index'].max(), 100)
axes[1].plot(xr, m * xr + b, color='crimson', linewidth=2)
axes[1].set_xlabel('Nottingham Prognostic Index')
axes[1].set_ylabel('Overall Survival (Months)')
axes[1].set_title(f'NPI vs Survival  rho={r_npi:.3f}  p={p_npi:.2e}')

sub2 = df_clean[['Tumor Size',
                 'Lymph nodes examined positive']].dropna()
r2, p2 = spearmanr(sub2['Tumor Size'],
                   sub2['Lymph nodes examined positive'])
axes[2].scatter(sub2['Tumor Size'],
                sub2['Lymph nodes examined positive'],
                alpha=0.1, s=4, color=PURPL)
m2, b2 = np.polyfit(sub2['Tumor Size'],
                    sub2['Lymph nodes examined positive'], 1)
x2 = np.linspace(sub2['Tumor Size'].min(), sub2['Tumor Size'].max(), 100)
axes[2].plot(x2, m2 * x2 + b2, color='crimson', linewidth=2)
axes[2].set_xlabel('Tumor Size (mm)')
axes[2].set_ylabel('Positive Lymph Nodes')
axes[2].set_title(f'Tumor Size vs Lymph Nodes  rho={r2:.3f}  p={p2:.2e}')

plt.tight_layout()
plt.savefig('correlation_results.png', bbox_inches='tight')
plt.show()

"""# Stage 2"""

print(df_clean['Overall Survival Status'].value_counts())

print(df_clean['Patient\'s Vital Status'].value_counts())

print(df_clean['Relapse Free Status'].value_counts())

print(df_clean[['Overall Survival (Months)',
                'Relapse Free Status (Months)']].describe())

vars_to_check = [

    'Tumor Stage',

    'Neoplasm Histologic Grade',

    'Hormone Therapy',

    'Chemotherapy',

    'HER2 Status',

    'ER Status',

    'PR Status',

    'Type of Breast Surgery',

    'Inferred Menopausal State',

    'Radio Therapy',

    'triple_negative'

]

for col in vars_to_check:

    print("\n")
    print("="*60)

    print(col)

    print("="*60)

    print(df_clean[col].value_counts(dropna=False))

important_vars = [
    'Tumor Stage',
    'Neoplasm Histologic Grade',
    'Hormone Therapy',
    'Chemotherapy',
    'HER2 Status'
]

for col in important_vars:
    print("\n")
    print("="*60)
    print(col)
    print("="*60)
    print(df_clean[col].value_counts(dropna=False))

cox_vars = [

    'Age at Diagnosis',
    'Tumor Stage',
    'Neoplasm Histologic Grade',
    'Tumor Size',
    'Lymph nodes examined positive',
    'Mutation Count',
    'Nottingham prognostic index'

]

print(
    df_clean[cox_vars]
    .describe()
)

corr_cols = [

    'Tumor Stage',
    'Neoplasm Histologic Grade',
    'Tumor Size',
    'Lymph nodes examined positive',
    'Mutation Count',
    'Nottingham prognostic index'

]

print(
    df_clean[corr_cols]
    .corr()
    .round(2)
)

df_surv = df_clean.copy()

# Overall Survival Time
df_surv['OS_time'] = df_surv['Overall Survival (Months)']

# Event Variable
df_surv['OS_event'] = (
    df_surv['Overall Survival Status']
      .eq('Deceased')
      .astype(int)
)

print("Deaths :", df_surv['OS_event'].sum())
print("Living :", (df_surv['OS_event'] == 0).sum())

# Commented out IPython magic to ensure Python compatibility.
# Install the lifelines library if not already installed
# %pip install lifelines

from lifelines import KaplanMeierFitter
import matplotlib.pyplot as plt

kmf = KaplanMeierFitter()

plt.figure(figsize=(10,6))

for stage in sorted(df_surv['Tumor Stage'].dropna().unique()):

    mask = df_surv['Tumor Stage'] == stage

    kmf.fit(
        durations=df_surv.loc[mask, 'OS_time'],
        event_observed=df_surv.loc[mask, 'OS_event'],
        label=f'Stage {int(stage)}'
    )

    kmf.plot_survival_function()

plt.title('Overall Survival by Tumor Stage')
plt.xlabel('Months')
plt.ylabel('Survival Probability')
plt.grid(True)

plt.show()

"""# Log rank test"""

from lifelines.statistics import multivariate_logrank_test

result = multivariate_logrank_test(
    event_durations=df_surv['OS_time'],
    groups=df_surv['Tumor Stage'],
    event_observed=df_surv['OS_event']
)

print(result)

"""# Keplan meier"""

from lifelines import KaplanMeierFitter
import matplotlib.pyplot as plt

kmf = KaplanMeierFitter()

plt.figure(figsize=(10,6))

for grp in df_surv['Hormone Therapy'].dropna().unique():

    mask = df_surv['Hormone Therapy'] == grp

    kmf.fit(
        durations=df_surv.loc[mask, 'OS_time'],
        event_observed=df_surv.loc[mask, 'OS_event'],
        label=f'Hormone Therapy = {grp}'
    )

    kmf.plot_survival_function()

plt.title('Overall Survival by Hormone Therapy')
plt.xlabel('Months')
plt.ylabel('Survival Probability')
plt.grid(True)

plt.show()

from lifelines.statistics import logrank_test

yes_group = df_surv[df_surv['Hormone Therapy'] == 'Yes']
no_group  = df_surv[df_surv['Hormone Therapy'] == 'No']

result = logrank_test(
    yes_group['OS_time'],
    no_group['OS_time'],
    event_observed_A=yes_group['OS_event'],
    event_observed_B=no_group['OS_event']
)

print(result)

print(df_surv.columns)

"""# Univariate cox Regression"""

from lifelines import CoxPHFitter
import pandas as pd

cox_vars = [
    'Age at Diagnosis',
    'Tumor Stage',
    'Neoplasm Histologic Grade',
    'Tumor Size',
    'Lymph nodes examined positive',
    'Mutation Count',
    'Hormone Therapy_bin',
    'Chemotherapy_bin',
    'ER_pos',
    'PR_pos',
    'HER2_pos',
    'triple_negative'
]

uni_results = []

for var in cox_vars:

    temp = df_surv[['OS_time', 'OS_event', var]].dropna()

    cph = CoxPHFitter()

    cph.fit(
        temp,
        duration_col='OS_time',
        event_col='OS_event'
    )

    summary = cph.summary

    uni_results.append({
        'Variable': var,
        'HR': summary.loc[var, 'exp(coef)'],
        'Lower95CI': summary.loc[var, 'exp(coef) lower 95%'],
        'Upper95CI': summary.loc[var, 'exp(coef) upper 95%'],
        'p_value': summary.loc[var, 'p']
    })

univariate_results = pd.DataFrame(uni_results)

univariate_results = (
    univariate_results
    .sort_values('HR', ascending=False)
)

print(univariate_results.round(4))

"""# Multivariater cox regression"""

from lifelines import CoxPHFitter

multi_vars = [

    'Age at Diagnosis',

    'Tumor Stage',

    'Neoplasm Histologic Grade',

    'Tumor Size',

    'Lymph nodes examined positive',

    'Mutation Count',

    'Hormone Therapy_bin',

    'Chemotherapy_bin',

    'ER_pos',

    'PR_pos',

    'HER2_pos'
]

multi_df = (
    df_surv[
        ['OS_time', 'OS_event'] + multi_vars
    ]
    .dropna()
)

cph = CoxPHFitter()

cph.fit(
    multi_df,
    duration_col='OS_time',
    event_col='OS_event'
)

cph.print_summary()

cph.summary[
    [
        'coef',
        'exp(coef)',
        'exp(coef) lower 95%',
        'exp(coef) upper 95%',
        'p'
    ]
]

pd.crosstab(
    df_surv['Hormone Therapy'],
    df_surv['ER Status'],
    margins=True
)

pd.crosstab(
    df_surv['Hormone Therapy'],
    df_surv['Tumor Stage'],
    margins=True
)

pd.crosstab(
    df_surv['Hormone Therapy'],
    df_surv['Overall Survival Status'],
    margins=True
)

from lifelines import CoxPHFitter

test_vars = [
    'Age at Diagnosis',
    'Tumor Stage',
    'Tumor Size',
    'Lymph nodes examined positive',
    'Hormone Therapy_bin',
    'HER2_pos'
]

test_df = df_surv[
    ['OS_time','OS_event'] + test_vars
].dropna()

cph2 = CoxPHFitter()

cph2.fit(
    test_df,
    duration_col='OS_time',
    event_col='OS_event'
)

cph2.summary[['exp(coef)','p']]

# Age Groups
df_surv['Age_Group'] = pd.cut(
    df_surv['Age at Diagnosis'],
    bins=[0, 40, 60, 100],
    labels=['<40', '40-60', '>60']
)

# Tumor Size Groups
df_surv['Tumor_Size_Group'] = pd.cut(
    df_surv['Tumor Size'],
    bins=[0, 20, 50, 200],
    labels=['Small', 'Medium', 'Large']
)

# Lymph Node Groups
df_surv['Node_Group'] = pd.cut(
    df_surv['Lymph nodes examined positive'],
    bins=[-1, 0, 3, 100],
    labels=['0', '1-3', '>3']
)

print("\nAge Groups")
print(df_surv['Age_Group'].value_counts())

print("\nTumor Size Groups")
print(df_surv['Tumor_Size_Group'].value_counts())

print("\nNode Groups")
print(df_surv['Node_Group'].value_counts())

print(df_surv['Age_Group'].value_counts())
print(df_surv['Tumor_Size_Group'].value_counts())
print(df_surv['Node_Group'].value_counts())

from lifelines import CoxPHFitter
import pandas as pd

# Dummy Variables
cox_df = pd.get_dummies(
    df_surv,
    columns=[
        'Age_Group',
        'Tumor_Size_Group',
        'Node_Group'
    ],
    drop_first=True
)

model_vars = [

    'Hormone Therapy_bin',
    'Chemotherapy_bin',

    'ER_pos',
    'PR_pos',
    'HER2_pos',

    'Mutation Count',

    'Age_Group_40-60',
    'Age_Group_>60',

    'Tumor_Size_Group_Medium',
    'Tumor_Size_Group_Large',

    'Node_Group_1-3',
    'Node_Group_>3'
]

strat_df = cox_df[
    ['OS_time',
     'OS_event',
     'Tumor Stage',
     'Neoplasm Histologic Grade']
    + model_vars
].dropna()

cph_strat = CoxPHFitter()

cph_strat.fit(
    strat_df,
    duration_col='OS_time',
    event_col='OS_event',
    strata=[
        'Tumor Stage',
        'Neoplasm Histologic Grade'
    ]
)

cph_strat.summary[
    [
        'exp(coef)',
        'exp(coef) lower 95%',
        'exp(coef) upper 95%',
        'p'
    ]
].sort_values(
    'exp(coef)',
    ascending=False
)

cph_strat.check_assumptions(
    strat_df,
    p_value_threshold=0.05,
    show_plots=False
)

import matplotlib.pyplot as plt
import numpy as np

# Extract results
df_forest = cph_strat.summary.copy()

df_forest = df_forest[
    ['exp(coef)',
     'exp(coef) lower 95%',
     'exp(coef) upper 95%']
]

df_forest = df_forest.sort_values('exp(coef)')

# Plot setup
plt.figure(figsize=(10, 8))

y_pos = np.arange(len(df_forest))

hr = df_forest['exp(coef)']
lower = df_forest['exp(coef) lower 95%']
upper = df_forest['exp(coef) upper 95%']

# Error bars (CI)
plt.errorbar(
    hr,
    y_pos,
    xerr=[hr - lower, upper - hr],
    fmt='o',
    color='black',
    ecolor='gray',
    capsize=4
)

# Reference line (no effect line)
plt.axvline(x=1, color='red', linestyle='--')

plt.yticks(y_pos, df_forest.index)
plt.xlabel("Hazard Ratio (HR)")
plt.title("Forest Plot - Stratified Cox Model")
plt.grid(True, axis='x', linestyle='--', alpha=0.5)

plt.show()

from lifelines import CoxPHFitter

cph = CoxPHFitter()

strata_cols = [
    'Hormone Therapy_bin',
    'Chemotherapy_bin',
    'ER_pos',
    'PR_pos',
    'Age_Group_40-60',
    'Age_Group_>60',
    'Tumor_Size_Group_Medium',
    'Tumor_Size_Group_Large',
    'Node_Group_1-3',
    'Node_Group_>3',
]

# Select only the necessary columns for the Cox model
model_df = cox_df[['OS_time', 'OS_event'] + strata_cols].dropna()

cph.fit(
    model_df,
    duration_col='OS_time',
    event_col='OS_event',
    strata=strata_cols
)

import pandas as pd

# Bin mutation count into categories
df['Mutation_Count_bin'] = pd.cut(
    df['Mutation Count'],
    bins=[0, 5, 10, 20, float('inf')],
    labels=['Low', 'Medium', 'High', 'Very High']
)

# Then add to strata
strata_vars = [..., 'Mutation_Count_bin']

import numpy as np

# Create time-varying term using the correct survival time column from df_surv
df_surv['Mutation_Count_x_logT'] = df_surv['Mutation Count'] * np.log(df_surv['OS_time'])

# The formula in `cph.fit` needs to be completed with relevant variables after the time-varying term.
# For now, I'll use a placeholder for other variables.
# Also, ensure 'cph' is an initialized CoxPHFitter object, and use df_surv.
# cph.fit(df_surv, duration_col='OS_time', event_col='OS_event',
#         formula="Mutation_Count_x_logT + HER2_pos + ...")

# This cell is no longer needed as we will use df_surv directly for the AFT model.

# This cell is no longer needed as we will use df_surv directly for the AFT model, and its OS_event column is already binary (0/1).

# This cell is no longer needed as we will use df_surv directly for the AFT model, and its OS_event column is already binary (0/1).

from lifelines import WeibullAFTFitter

aft = WeibullAFTFitter()

# Define the columns used in the AFT model formula
all_model_cols = [
    'OS_time', 'OS_event', 'Age at Diagnosis', 'HER2_pos',
    'Mutation Count', 'Chemotherapy_bin', 'Hormone Therapy_bin',
    'ER_pos', 'PR_pos', 'Tumor_Size_Group', 'Node_Group'
]

# Create a new DataFrame by dropping NaNs from the relevant columns
aft_df = df_surv[all_model_cols].dropna()

# Ensure all durations are strictly positive
aft_df['OS_time'] = aft_df['OS_time'].apply(lambda x: max(x, 1e-6))

aft.fit(
    aft_df, # Using aft_df with NaNs dropped
    duration_col='OS_time',
    event_col='OS_event',
    formula="""
        `Age at Diagnosis` +
        HER2_pos +
        `Mutation Count` +
        Chemotherapy_bin +
        `Hormone Therapy_bin` +
        ER_pos +
        PR_pos +
        Tumor_Size_Group +
        Node_Group
    """
)

aft.print_summary()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# =========================
# Extract AFT results
# =========================
summary = aft.summary.copy()
summary = summary.loc["lambda_"]
summary = summary[summary.index != "Intercept"]

# =========================
# Create dataframe
# =========================
df_plot = pd.DataFrame({
    "variable": summary.index,
    "time_ratio": summary["exp(coef)"],
    "lower": summary["exp(coef) lower 95%"],
    "upper": summary["exp(coef) upper 95%"],
    "p": summary["p"]
})

# =========================
# Clean labels (IMPORTANT)
# =========================
label_map = {
    "Tumor_Size_Group[T.Medium]": "Tumor Size: Medium",
    "Tumor_Size_Group[T.Large]": "Tumor Size: Large",
    "Node_Group[T.1-3]": "Nodes: 1–3",
    "Node_Group[T.>3]": "Nodes: >3"
}

df_plot["variable"] = df_plot["variable"].replace(label_map)

# =========================
# Sort by effect size
# =========================
df_plot = df_plot.sort_values("time_ratio")

# =========================
# Plot
# =========================
plt.figure(figsize=(10, 6))
y = np.arange(len(df_plot))

plt.errorbar(
    df_plot["time_ratio"],
    y,
    xerr=[
        df_plot["time_ratio"] - df_plot["lower"],
        df_plot["upper"] - df_plot["time_ratio"]
    ],
    fmt='o',
    color='black',
    ecolor='gray',
    capsize=4
)

plt.axvline(1, linestyle="--", color="red")

plt.yticks(y, df_plot["variable"])
plt.xlabel("Time Ratio (Acceleration Factor)")
plt.title("AFT Model Forest Plot (Clean Clinical Interpretation)")
plt.grid(axis='x', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()

